2019-07-22 10:42:01,597 CRITICAL exception_function => Exception on handling exception_function with args=() kwargs={}
Traceback (most recent call last):
  File "using_exc_info.py", line 8, in exception_function
    1 / 0
ZeroDivisionError: division by zero
